#!/bin/bash

#set -x -v

[ -z "$1" ] && exit

childs ()
{
	CHILDS="$(ps ho pid --ppid $@)"
	for SIBLING in $CHILDS; do
		if [ -n "$SIBLING" ]; then
			echo -n "$SIBLING "
			childs $SIBLING;
		fi
	done
}

echo -n "$@ "
childs $@

